---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-70
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
