# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
before_install:
  # This is required since 2.6.8 has issue when installing `rainbow`
  # https://github.com/sickill/rainbow/issues/48
  - gem update --system
  - gem --version
cache:
  - bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
gemfile:
  - gemfiles/contracts_15_0.gemfile
  - gemfiles/contracts_16_0.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
